### ISSUE TITLE
Buttons are broken in v1.7

### ISSUE THREAD

**Issue by ShroomKing** [Ibrahim778/QuickMenuReborn#2]
Just updated to v1.7 and Buttons no longer work. Every time you press a button the Vita freezes and then reboots after some time.

This also happens with the sample you uploaded.

Not sure if its a bug or sample code needs to be updated but i have to go back to v1.6 for now cuz everything works there.

**Comment by Ibrahim778** [comment]
Oh. So it's not just one random plugin I made months ago. I'll check it out thanks.

**Comment by Ibrahim778** [comment]
hmm. Do me a favour. Update your quickmenureborn dev library stubs and files to V1.7 and recompile.

**Comment by ShroomKing** [comment]
Thats what i did but it still didn't work.
I'm using the vitasdk stubs btw. Not sure if that changes anything.

**Comment by Ibrahim778** [comment]
It doesn't I fixed it. Uploading new release now...

**Comment by ShroomKing** [comment]
Alright thank you so much!
