### ISSUE TITLE
Cant compile my Project

### ISSUE THREAD

**Issue by ghost** [Ibrahim778/QuickMenuReborn#3]
So, i have vitaSDK installed with vdsuite QuickMenuReborn stubs and it doesn't work
It says:

```
CMake Error at build/CMakeFiles/3.21.0/CMakeSystem.cmake:6 (include):
  include could not find requested file:

    /host_tools/build/cmake/psp2-snc-toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)


-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
System is unknown to cmake, create:
Platform/PSP2 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please post that file on discourse.cmake.org.
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    /host_tools/build/bin/psp2snc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_CXX_COMPILER:

    /host_tools/build/bin/psp2snc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

Is it just me or am i dumb? Since i'm trying to learn how to use this. (yeah im a noob)

**Comment by Ibrahim778** [comment]
Your CMakeLists.txt file seems broken
Also you say you're using VitaSDK but the file /host_tools/build/bin/psp2snc.exe is from SCE_PSP2_SDK which is only used by VDSuite!
To use this with vitaSDK use a standard VitaSDK CMakeLists file and just link with QuickMenuReborn

EDIT: Also you're meant to use VItaSDK stubs with VitaSDK

**Comment by ghost** [comment]
Oh well how do i do that? (sorry if i sound annoying or something, i'm just new to this)

**Comment by Ibrahim778** [comment]
How do you do what? Link the stubs or make the CMake File?

**Comment by ghost** [comment]
Both, since i'm new at making a plugin from quickmenureborn and editing the CMake File. (sorry for a little late responce since i didn't notice you)

**Comment by Ibrahim778** [comment]
Sounds to me like you don't know how to make a plugin. VitaSDK has an example here: https://github.com/vitasdk/samples/tree/master/prx_simple
Base your CMake file off of this one and not the one I have in the QuickMenuReborn repo.

As for linking to QuickMenuReborn you need to first install the stubs and headers. Re-read the instructions but make sure to use the stubs inside vitasdk-stubs and not stubs, Then once you have made your project you simply need to add QuickMenuReborn_stub in the target_link_libraries function in the cmake file

**Comment by ghost** [comment]
Well i did get further but this appears:

```
error: unknown type name 'bool'
   29 | bool resetOnExit = false;
      | ^~~~

error: 'false' undeclared here (not in a function)
   29 | bool resetOnExit = false;
      |                    ^~~~~
```
with main.c

**Comment by ghost** [comment]
Also is the emd file important?

**Comment by Ibrahim778** [comment]
Include stdbool.h, No you don't need to care about the .emd, it's only used in vdsuite

**Comment by ghost** [comment]
I think i did i it. (I just changed 1 thing in it)
[sampleplugin.zip](https://github.com/Ibrahim778/QuickMenuReborn/files/7634979/sampleplugin.zip)
I'm gonna test it.

**Comment by ghost** [comment]
Nope, it just freezes in the loading screen.

**Comment by ghost** [comment]
Continuation: #4
