### ISSUE TITLE
Vita freezes after i put my plugin in it

### ISSUE THREAD

**Issue by ghost** [Ibrahim778/QuickMenuReborn#4]

**Comment by Ibrahim778** [comment]
(It means your plugin is crashing)

**Comment by Ibrahim778** [comment]
Make a repo and show me the project files. It seems broken
Also how are you installing the plugin?

**Comment by ghost** [comment]
Just like the instructions says

**Comment by ghost** [comment]
https://github.com/hedhehd/Sample_Quickmenureborn/tree/main

**Comment by Ibrahim778** [comment]
So you're installing by putting it in the QuickMenuReborn folder, right?

**Comment by Ibrahim778** [comment]
Only thing left is that it could be bad stubs, are you *sure* you're using the vitasdk-stubs and not vdsuite ones?

**Comment by ghost** [comment]
I dont know. I'll check.

**Comment by ghost** [comment]
Yes i am

**Comment by ghost** [comment]
Maybe because i typed in the cmake file Quickmenureborn_stub and not weak?

**Comment by ghost** [comment]
But still, it doesn't work

**Comment by ghost** [comment]
> Only thing left is that it could be bad stubs, are you _sure_ you're using the vitasdk-stubs and not vdsuite ones?

Yes.

**Comment by Ibrahim778** [comment]
How are you so sure it's the vitasdk-stubs?
You should link to QuickMenuReborn_stub not _weak.

**Comment by ghost** [comment]
Oh but i did and it still doesn't work.

> How are you so sure it's the vitasdk-stubs? You should link to QuickMenuReborn_stub not _weak.

Because i copied the vitasdk stubs again from the dev-pkg.zip

**Comment by Ibrahim778** [comment]
Ok.....maybe vitasdk stubs are broken?
Shouldn't be happening...I'll remake them and send them

**Comment by Ibrahim778** [comment]
Here, try these.
[vitasdk_stubs.zip](https://github.com/Ibrahim778/QuickMenuReborn/files/7642097/vitasdk_stubs.zip)

**Comment by ghost** [comment]
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld.exe: warning: cannot find entry symbol _start; defaulting to 0000000081000000

is this supposed to happen?

**Comment by ghost** [comment]
It still freezes... Weird

**Comment by Ibrahim778** [comment]
> c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld.exe: warning: cannot find entry symbol _start; defaulting to 0000000081000000
> 
> is this supposed to happen?

No. I remember now. VitaSDK needs another entry point. One second.

**Comment by Ibrahim778** [comment]
Add this just above module_start in your main.c file.
`void _start() __attribute__((weak, alias("module_start")));
`

**Comment by ghost** [comment]
Like this?:

```
BUTTON_HANDLER(OnToggleCheckBox)
{
    resetOnExit = QuickMenuRebornGetCheckboxValue(CHECKBOX_REF_ID);
}
void _start() __attribute__((weak, alias("module_start")));
int module_start()
{
    QuickMenuRebornSeparator(SEPARATOR_ID, SCE_SEPARATOR_HEIGHT);

```

**Comment by Ibrahim778** [comment]
Yup

**Comment by ghost** [comment]
Okay im gonna try

**Comment by ghost** [comment]
Oh now it doesn't say that warning

**Comment by Ibrahim778** [comment]
Then it should be fixed.

**Comment by ghost** [comment]
Yep it did. Anyway's thanks for the help!

**Comment by Ibrahim778** [comment]
You're Welcome.
